/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-03-18 19:43:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.desafiosea.todo.model.Task;
import java.util.List;
import java.util.Map;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/init.jsp", Long.valueOf(1773851950000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.desafiosea.todo.model.Task");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  liferay-theme:defineObjects
      com.liferay.taglib.theme.DefineObjectsTag _jspx_th_liferay_002dtheme_005fdefineObjects_005f0 = new com.liferay.taglib.theme.DefineObjectsTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0);
      _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
      _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setParent(null);
      int _jspx_eval_liferay_002dtheme_005fdefineObjects_005f0 = _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doStartTag();
      if (_jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0, _jsp_getInstanceManager());
      com.liferay.portal.kernel.theme.ThemeDisplay themeDisplay = null;
      com.liferay.portal.kernel.model.Company company = null;
      com.liferay.portal.kernel.model.User user = null;
      com.liferay.portal.kernel.model.User realUser = null;
      com.liferay.portal.kernel.model.Contact contact = null;
      com.liferay.portal.kernel.model.Layout layout = null;
      java.util.List layouts = null;
      java.lang.Long plid = null;
      com.liferay.portal.kernel.model.LayoutTypePortlet layoutTypePortlet = null;
      java.lang.Long scopeGroupId = null;
      com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker = null;
      java.util.Locale locale = null;
      java.util.TimeZone timeZone = null;
      com.liferay.portal.kernel.model.Theme theme = null;
      com.liferay.portal.kernel.model.ColorScheme colorScheme = null;
      com.liferay.portal.kernel.theme.PortletDisplay portletDisplay = null;
      java.lang.Long portletGroupId = null;
      themeDisplay = (com.liferay.portal.kernel.theme.ThemeDisplay) _jspx_page_context.findAttribute("themeDisplay");
      company = (com.liferay.portal.kernel.model.Company) _jspx_page_context.findAttribute("company");
      user = (com.liferay.portal.kernel.model.User) _jspx_page_context.findAttribute("user");
      realUser = (com.liferay.portal.kernel.model.User) _jspx_page_context.findAttribute("realUser");
      contact = (com.liferay.portal.kernel.model.Contact) _jspx_page_context.findAttribute("contact");
      layout = (com.liferay.portal.kernel.model.Layout) _jspx_page_context.findAttribute("layout");
      layouts = (java.util.List) _jspx_page_context.findAttribute("layouts");
      plid = (java.lang.Long) _jspx_page_context.findAttribute("plid");
      layoutTypePortlet = (com.liferay.portal.kernel.model.LayoutTypePortlet) _jspx_page_context.findAttribute("layoutTypePortlet");
      scopeGroupId = (java.lang.Long) _jspx_page_context.findAttribute("scopeGroupId");
      permissionChecker = (com.liferay.portal.kernel.security.permission.PermissionChecker) _jspx_page_context.findAttribute("permissionChecker");
      locale = (java.util.Locale) _jspx_page_context.findAttribute("locale");
      timeZone = (java.util.TimeZone) _jspx_page_context.findAttribute("timeZone");
      theme = (com.liferay.portal.kernel.model.Theme) _jspx_page_context.findAttribute("theme");
      colorScheme = (com.liferay.portal.kernel.model.ColorScheme) _jspx_page_context.findAttribute("colorScheme");
      portletDisplay = (com.liferay.portal.kernel.theme.PortletDisplay) _jspx_page_context.findAttribute("portletDisplay");
      portletGroupId = (java.lang.Long) _jspx_page_context.findAttribute("portletGroupId");
      out.write('\n');
      out.write('\n');
      //  portlet:defineObjects
      com.liferay.taglib.portlet.DefineObjectsTag _jspx_th_portlet_005fdefineObjects_005f0 = new com.liferay.taglib.portlet.DefineObjectsTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fdefineObjects_005f0);
      _jspx_th_portlet_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005fdefineObjects_005f0.setParent(null);
      int _jspx_eval_portlet_005fdefineObjects_005f0 = _jspx_th_portlet_005fdefineObjects_005f0.doStartTag();
      if (_jspx_th_portlet_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fdefineObjects_005f0, _jsp_getInstanceManager());
      javax.portlet.ActionRequest actionRequest = null;
      javax.portlet.ActionResponse actionResponse = null;
      javax.portlet.EventRequest eventRequest = null;
      javax.portlet.EventResponse eventResponse = null;
      com.liferay.portal.kernel.portlet.LiferayPortletRequest liferayPortletRequest = null;
      com.liferay.portal.kernel.portlet.LiferayPortletResponse liferayPortletResponse = null;
      javax.portlet.PortletConfig portletConfig = null;
      java.lang.String portletName = null;
      javax.portlet.PortletPreferences portletPreferences = null;
      java.util.Map portletPreferencesValues = null;
      javax.portlet.PortletSession portletSession = null;
      java.util.Map portletSessionScope = null;
      javax.portlet.RenderRequest renderRequest = null;
      javax.portlet.RenderResponse renderResponse = null;
      javax.portlet.ResourceRequest resourceRequest = null;
      javax.portlet.ResourceResponse resourceResponse = null;
      actionRequest = (javax.portlet.ActionRequest) _jspx_page_context.findAttribute("actionRequest");
      actionResponse = (javax.portlet.ActionResponse) _jspx_page_context.findAttribute("actionResponse");
      eventRequest = (javax.portlet.EventRequest) _jspx_page_context.findAttribute("eventRequest");
      eventResponse = (javax.portlet.EventResponse) _jspx_page_context.findAttribute("eventResponse");
      liferayPortletRequest = (com.liferay.portal.kernel.portlet.LiferayPortletRequest) _jspx_page_context.findAttribute("liferayPortletRequest");
      liferayPortletResponse = (com.liferay.portal.kernel.portlet.LiferayPortletResponse) _jspx_page_context.findAttribute("liferayPortletResponse");
      portletConfig = (javax.portlet.PortletConfig) _jspx_page_context.findAttribute("portletConfig");
      portletName = (java.lang.String) _jspx_page_context.findAttribute("portletName");
      portletPreferences = (javax.portlet.PortletPreferences) _jspx_page_context.findAttribute("portletPreferences");
      portletPreferencesValues = (java.util.Map) _jspx_page_context.findAttribute("portletPreferencesValues");
      portletSession = (javax.portlet.PortletSession) _jspx_page_context.findAttribute("portletSession");
      portletSessionScope = (java.util.Map) _jspx_page_context.findAttribute("portletSessionScope");
      renderRequest = (javax.portlet.RenderRequest) _jspx_page_context.findAttribute("renderRequest");
      renderResponse = (javax.portlet.RenderResponse) _jspx_page_context.findAttribute("renderResponse");
      resourceRequest = (javax.portlet.ResourceRequest) _jspx_page_context.findAttribute("resourceRequest");
      resourceResponse = (javax.portlet.ResourceResponse) _jspx_page_context.findAttribute("resourceResponse");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  liferay-ui:error
      com.liferay.taglib.ui.ErrorTag _jspx_th_liferay_002dui_005ferror_005f0 = new com.liferay.taglib.ui.ErrorTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dui_005ferror_005f0);
      _jspx_th_liferay_002dui_005ferror_005f0.setPageContext(_jspx_page_context);
      _jspx_th_liferay_002dui_005ferror_005f0.setParent(null);
      // /view.jsp(8,0) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_liferay_002dui_005ferror_005f0.setKey("task-permission-denied");
      // /view.jsp(8,0) name = message type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_liferay_002dui_005ferror_005f0.setMessage("Você não tem permissão para modificar esta tarefa.");
      int _jspx_eval_liferay_002dui_005ferror_005f0 = _jspx_th_liferay_002dui_005ferror_005f0.doStartTag();
      if (_jspx_th_liferay_002dui_005ferror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dui_005ferror_005f0, _jsp_getInstanceManager());
      out.write('\n');
      //  liferay-ui:error
      com.liferay.taglib.ui.ErrorTag _jspx_th_liferay_002dui_005ferror_005f1 = new com.liferay.taglib.ui.ErrorTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dui_005ferror_005f1);
      _jspx_th_liferay_002dui_005ferror_005f1.setPageContext(_jspx_page_context);
      _jspx_th_liferay_002dui_005ferror_005f1.setParent(null);
      // /view.jsp(9,0) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_liferay_002dui_005ferror_005f1.setKey("task-delete-error");
      // /view.jsp(9,0) name = message type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_liferay_002dui_005ferror_005f1.setMessage("Ocorreu um erro ao deletar a tarefa.");
      int _jspx_eval_liferay_002dui_005ferror_005f1 = _jspx_th_liferay_002dui_005ferror_005f1.doStartTag();
      if (_jspx_th_liferay_002dui_005ferror_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dui_005ferror_005f1, _jsp_getInstanceManager());
      out.write('\n');
      //  liferay-ui:error
      com.liferay.taglib.ui.ErrorTag _jspx_th_liferay_002dui_005ferror_005f2 = new com.liferay.taglib.ui.ErrorTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dui_005ferror_005f2);
      _jspx_th_liferay_002dui_005ferror_005f2.setPageContext(_jspx_page_context);
      _jspx_th_liferay_002dui_005ferror_005f2.setParent(null);
      // /view.jsp(10,0) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_liferay_002dui_005ferror_005f2.setKey("task-toggle-error");
      // /view.jsp(10,0) name = message type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_liferay_002dui_005ferror_005f2.setMessage("Ocorreu um erro ao alterar o status da tarefa.");
      int _jspx_eval_liferay_002dui_005ferror_005f2 = _jspx_th_liferay_002dui_005ferror_005f2.doStartTag();
      if (_jspx_th_liferay_002dui_005ferror_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dui_005ferror_005f2, _jsp_getInstanceManager());
      out.write('\n');
      //  liferay-ui:error
      com.liferay.taglib.ui.ErrorTag _jspx_th_liferay_002dui_005ferror_005f3 = new com.liferay.taglib.ui.ErrorTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dui_005ferror_005f3);
      _jspx_th_liferay_002dui_005ferror_005f3.setPageContext(_jspx_page_context);
      _jspx_th_liferay_002dui_005ferror_005f3.setParent(null);
      // /view.jsp(11,0) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_liferay_002dui_005ferror_005f3.setKey("task-update-error");
      // /view.jsp(11,0) name = message type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_liferay_002dui_005ferror_005f3.setMessage("Ocorreu um erro ao atualizar a tarefa.");
      int _jspx_eval_liferay_002dui_005ferror_005f3 = _jspx_th_liferay_002dui_005ferror_005f3.doStartTag();
      if (_jspx_th_liferay_002dui_005ferror_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dui_005ferror_005f3, _jsp_getInstanceManager());
      out.write('\n');
      out.write('\n');

List<Task> rootTasks = (List<Task>)request.getAttribute("rootTasks");
Map<Long, List<Task>> subtasksByParentTaskId =
	(Map<Long, List<Task>>)request.getAttribute("subtasksByParentTaskId");
Map<Long, String> taskImageUrls =
	(Map<Long, String>)request.getAttribute("taskImageUrls");

int totalCount = (Integer)request.getAttribute("totalCount");
int pendingCount = (Integer)request.getAttribute("pendingCount");
int doneCount = (Integer)request.getAttribute("doneCount");
String currentFilter = (String)request.getAttribute("currentFilter");

if (currentFilter == null || currentFilter.isEmpty()) {
	currentFilter = "all";
}

String namespace = renderResponse.getNamespace();

      out.write('\n');
      out.write('\n');
      //  portlet:renderURL
      com.liferay.taglib.portlet.RenderURLTag _jspx_th_portlet_005frenderURL_005f0 = new com.liferay.taglib.portlet.RenderURLTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005frenderURL_005f0);
      _jspx_th_portlet_005frenderURL_005f0.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005frenderURL_005f0.setParent(null);
      // /view.jsp(32,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005frenderURL_005f0.setVar("newTaskURL");
      int _jspx_eval_portlet_005frenderURL_005f0 = _jspx_th_portlet_005frenderURL_005f0.doStartTag();
      if (_jspx_eval_portlet_005frenderURL_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write('\n');
        out.write('	');
        if (_jspx_meth_portlet_005fparam_005f0(_jspx_th_portlet_005frenderURL_005f0, _jspx_page_context))
          return;
        out.write('\n');
      }
      if (_jspx_th_portlet_005frenderURL_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005frenderURL_005f0, _jsp_getInstanceManager());
      java.lang.String newTaskURL = null;
      newTaskURL = (java.lang.String) _jspx_page_context.findAttribute("newTaskURL");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"task-page-container\">\n");
      out.write("	<div class=\"task-top-section\">\n");
      out.write("		<div class=\"task-header\">\n");
      out.write("			<div>\n");
      out.write("				<h2 class=\"task-page-title\">Minhas Tarefas</h2>\n");
      out.write("				<p class=\"task-page-subtitle\">Organize suas tarefas e acompanhe o progresso.</p>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<a\n");
      out.write("				class=\"btn btn-primary task-new-button\"\n");
      out.write("				id=\"");
      out.print( namespace );
      out.write("newTaskLink\"\n");
      out.write("				href=\"");
      out.print( newTaskURL.toString() );
      out.write('&');
      out.print( namespace );
      out.write("filter=");
      out.print( currentFilter );
      out.write("\"\n");
      out.write("			>\n");
      out.write("				Nova Tarefa\n");
      out.write("			</a>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<input type=\"hidden\" id=\"");
      out.print( namespace );
      out.write("currentFilter\" value=\"");
      out.print( currentFilter );
      out.write("\" />\n");
      out.write("\n");
      out.write("		<div class=\"task-tabs\" id=\"");
      out.print( namespace );
      out.write("taskTabs\">\n");
      out.write("			<button type=\"button\" class=\"task-tab\" data-filter=\"all\">\n");
      out.write("				Todas (");
      out.print( totalCount );
      out.write(")\n");
      out.write("			</button>\n");
      out.write("\n");
      out.write("			<button type=\"button\" class=\"task-tab\" data-filter=\"pending\">\n");
      out.write("				Pendentes (");
      out.print( pendingCount );
      out.write(")\n");
      out.write("			</button>\n");
      out.write("\n");
      out.write("			<button type=\"button\" class=\"task-tab\" data-filter=\"done\">\n");
      out.write("				Concluídas (");
      out.print( doneCount );
      out.write(")\n");
      out.write("			</button>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	");
 if (rootTasks == null || rootTasks.isEmpty()) { 
      out.write("\n");
      out.write("		<div class=\"task-empty-card\">\n");
      out.write("			<p class=\"task-empty-title\">Nenhuma tarefa cadastrada ainda.</p>\n");
      out.write("			<p class=\"task-empty-subtitle\">Crie sua primeira tarefa para começar a organizar seu dia.</p>\n");
      out.write("		</div>\n");
      out.write("	");
 } else { 
      out.write("\n");
      out.write("		<ul class=\"task-list\" id=\"");
      out.print( namespace );
      out.write("taskList\">\n");
      out.write("			");
 for (Task task : rootTasks) { 
      out.write("\n");
      out.write("				");

				String imageURL = null;

				if (taskImageUrls != null) {
					imageURL = taskImageUrls.get(task.getTaskId());
				}

				List<Task> subtasks = null;

				if (subtasksByParentTaskId != null) {
					subtasks = subtasksByParentTaskId.get(task.getTaskId());
				}
				
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"task-item\" data-status=\"");
      out.print( task.isDone() ? "done" : "pending" );
      out.write("\">\n");
      out.write("					<div class=\"task-item-header\">\n");
      out.write("						<div class=\"task-item-main\">\n");
      out.write("							<h3 class=\"task-title\">");
      out.print( task.getTitle() );
      out.write("</h3>\n");
      out.write("\n");
      out.write("							");
 if (task.getDescription() != null && !task.getDescription().trim().isEmpty()) { 
      out.write("\n");
      out.write("								<p class=\"task-description\">");
      out.print( task.getDescription() );
      out.write("</p>\n");
      out.write("							");
 } 
      out.write("\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<span class=\"task-status-badge ");
      out.print( task.isDone() ? "task-status-done" : "task-status-pending" );
      out.write("\">\n");
      out.write("							");
      out.print( task.isDone() ? "Concluída" : "Pendente" );
      out.write("\n");
      out.write("						</span>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					");
 if (imageURL != null && !imageURL.isEmpty()) { 
      out.write("\n");
      out.write("						<div class=\"task-image-wrapper\">\n");
      out.write("							<img\n");
      out.write("								src=\"");
      out.print( imageURL );
      out.write("\"\n");
      out.write("								alt=\"Imagem da tarefa\"\n");
      out.write("								class=\"task-image\"\n");
      out.write("							/>\n");
      out.write("						</div>\n");
      out.write("					");
 } 
      out.write("\n");
      out.write("\n");
      out.write("					");
      //  portlet:renderURL
      com.liferay.taglib.portlet.RenderURLTag _jspx_th_portlet_005frenderURL_005f1 = new com.liferay.taglib.portlet.RenderURLTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005frenderURL_005f1);
      _jspx_th_portlet_005frenderURL_005f1.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005frenderURL_005f1.setParent(null);
      // /view.jsp(117,5) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005frenderURL_005f1.setVar("editTaskURL");
      int _jspx_eval_portlet_005frenderURL_005f1 = _jspx_th_portlet_005frenderURL_005f1.doStartTag();
      if (_jspx_eval_portlet_005frenderURL_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("						");
        if (_jspx_meth_portlet_005fparam_005f1(_jspx_th_portlet_005frenderURL_005f1, _jspx_page_context))
          return;
        out.write("\n");
        out.write("						");
        //  portlet:param
        com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f2 = new com.liferay.taglib.util.ParamTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f2);
        _jspx_th_portlet_005fparam_005f2.setPageContext(_jspx_page_context);
        _jspx_th_portlet_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005frenderURL_005f1);
        // /view.jsp(119,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f2.setName("taskId");
        // /view.jsp(119,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f2.setValue( String.valueOf(task.getTaskId()) );
        int _jspx_eval_portlet_005fparam_005f2 = _jspx_th_portlet_005fparam_005f2.doStartTag();
        if (_jspx_th_portlet_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f2, _jsp_getInstanceManager());
        out.write("\n");
        out.write("					");
      }
      if (_jspx_th_portlet_005frenderURL_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005frenderURL_005f1, _jsp_getInstanceManager());
      java.lang.String editTaskURL = null;
      editTaskURL = (java.lang.String) _jspx_page_context.findAttribute("editTaskURL");
      out.write("\n");
      out.write("\n");
      out.write("					");
      //  portlet:renderURL
      com.liferay.taglib.portlet.RenderURLTag _jspx_th_portlet_005frenderURL_005f2 = new com.liferay.taglib.portlet.RenderURLTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005frenderURL_005f2);
      _jspx_th_portlet_005frenderURL_005f2.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005frenderURL_005f2.setParent(null);
      // /view.jsp(122,5) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005frenderURL_005f2.setVar("newSubtaskURL");
      int _jspx_eval_portlet_005frenderURL_005f2 = _jspx_th_portlet_005frenderURL_005f2.doStartTag();
      if (_jspx_eval_portlet_005frenderURL_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("						");
        if (_jspx_meth_portlet_005fparam_005f3(_jspx_th_portlet_005frenderURL_005f2, _jspx_page_context))
          return;
        out.write("\n");
        out.write("						");
        //  portlet:param
        com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f4 = new com.liferay.taglib.util.ParamTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f4);
        _jspx_th_portlet_005fparam_005f4.setPageContext(_jspx_page_context);
        _jspx_th_portlet_005fparam_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005frenderURL_005f2);
        // /view.jsp(124,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f4.setName("parentTaskId");
        // /view.jsp(124,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f4.setValue( String.valueOf(task.getTaskId()) );
        int _jspx_eval_portlet_005fparam_005f4 = _jspx_th_portlet_005fparam_005f4.doStartTag();
        if (_jspx_th_portlet_005fparam_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f4, _jsp_getInstanceManager());
        out.write("\n");
        out.write("						");
        //  portlet:param
        com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f5 = new com.liferay.taglib.util.ParamTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f5);
        _jspx_th_portlet_005fparam_005f5.setPageContext(_jspx_page_context);
        _jspx_th_portlet_005fparam_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005frenderURL_005f2);
        // /view.jsp(125,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f5.setName("filter");
        // /view.jsp(125,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f5.setValue( currentFilter );
        int _jspx_eval_portlet_005fparam_005f5 = _jspx_th_portlet_005fparam_005f5.doStartTag();
        if (_jspx_th_portlet_005fparam_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f5, _jsp_getInstanceManager());
        out.write("\n");
        out.write("					");
      }
      if (_jspx_th_portlet_005frenderURL_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005frenderURL_005f2, _jsp_getInstanceManager());
      java.lang.String newSubtaskURL = null;
      newSubtaskURL = (java.lang.String) _jspx_page_context.findAttribute("newSubtaskURL");
      out.write("\n");
      out.write("\n");
      out.write("					");
      //  portlet:actionURL
      com.liferay.taglib.portlet.ActionURLTag _jspx_th_portlet_005factionURL_005f0 = new com.liferay.taglib.portlet.ActionURLTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005factionURL_005f0);
      _jspx_th_portlet_005factionURL_005f0.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005factionURL_005f0.setParent(null);
      // /view.jsp(128,5) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005factionURL_005f0.setName("/task/toggle-status");
      // /view.jsp(128,5) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005factionURL_005f0.setVar("toggleTaskStatusURL");
      int _jspx_eval_portlet_005factionURL_005f0 = _jspx_th_portlet_005factionURL_005f0.doStartTag();
      if (_jspx_eval_portlet_005factionURL_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("						");
        //  portlet:param
        com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f6 = new com.liferay.taglib.util.ParamTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f6);
        _jspx_th_portlet_005fparam_005f6.setPageContext(_jspx_page_context);
        _jspx_th_portlet_005fparam_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005factionURL_005f0);
        // /view.jsp(129,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f6.setName("taskId");
        // /view.jsp(129,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f6.setValue( String.valueOf(task.getTaskId()) );
        int _jspx_eval_portlet_005fparam_005f6 = _jspx_th_portlet_005fparam_005f6.doStartTag();
        if (_jspx_th_portlet_005fparam_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f6, _jsp_getInstanceManager());
        out.write("\n");
        out.write("					");
      }
      if (_jspx_th_portlet_005factionURL_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005factionURL_005f0, _jsp_getInstanceManager());
      java.lang.String toggleTaskStatusURL = null;
      toggleTaskStatusURL = (java.lang.String) _jspx_page_context.findAttribute("toggleTaskStatusURL");
      out.write("\n");
      out.write("\n");
      out.write("					");
      //  portlet:actionURL
      com.liferay.taglib.portlet.ActionURLTag _jspx_th_portlet_005factionURL_005f1 = new com.liferay.taglib.portlet.ActionURLTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005factionURL_005f1);
      _jspx_th_portlet_005factionURL_005f1.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005factionURL_005f1.setParent(null);
      // /view.jsp(132,5) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005factionURL_005f1.setName("/task/delete");
      // /view.jsp(132,5) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005factionURL_005f1.setVar("deleteTaskURL");
      int _jspx_eval_portlet_005factionURL_005f1 = _jspx_th_portlet_005factionURL_005f1.doStartTag();
      if (_jspx_eval_portlet_005factionURL_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("						");
        //  portlet:param
        com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f7 = new com.liferay.taglib.util.ParamTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f7);
        _jspx_th_portlet_005fparam_005f7.setPageContext(_jspx_page_context);
        _jspx_th_portlet_005fparam_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005factionURL_005f1);
        // /view.jsp(133,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f7.setName("taskId");
        // /view.jsp(133,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f7.setValue( String.valueOf(task.getTaskId()) );
        int _jspx_eval_portlet_005fparam_005f7 = _jspx_th_portlet_005fparam_005f7.doStartTag();
        if (_jspx_th_portlet_005fparam_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f7, _jsp_getInstanceManager());
        out.write("\n");
        out.write("					");
      }
      if (_jspx_th_portlet_005factionURL_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005factionURL_005f1, _jsp_getInstanceManager());
      java.lang.String deleteTaskURL = null;
      deleteTaskURL = (java.lang.String) _jspx_page_context.findAttribute("deleteTaskURL");
      out.write("\n");
      out.write("\n");
      out.write("					<div class=\"task-actions\">\n");
      out.write("						<a\n");
      out.write("							class=\"btn btn-secondary task-edit-link\"\n");
      out.write("							href=\"");
      out.print( editTaskURL.toString() );
      out.write('&');
      out.print( namespace );
      out.write("filter=");
      out.print( currentFilter );
      out.write("\"\n");
      out.write("						>\n");
      out.write("							Editar\n");
      out.write("						</a>\n");
      out.write("\n");
      out.write("						<a\n");
      out.write("							class=\"btn btn-light task-subtask-link\"\n");
      out.write("							href=\"");
      out.print( newSubtaskURL.toString() );
      out.write("\"\n");
      out.write("						>\n");
      out.write("							Adicionar Subtarefa\n");
      out.write("						</a>\n");
      out.write("\n");
      out.write("						");
      //  aui:form
      com.liferay.taglib.aui.FormTag _jspx_th_aui_005fform_005f0 = new com.liferay.taglib.aui.FormTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fform_005f0);
      _jspx_th_aui_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_aui_005fform_005f0.setParent(null);
      // /view.jsp(151,6) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f0.setAction( toggleTaskStatusURL );
      // /view.jsp(151,6) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f0.setMethod("post");
      // /view.jsp(151,6) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f0.setCssClass("d-inline task-filter-form");
      int _jspx_eval_aui_005fform_005f0 = _jspx_th_aui_005fform_005f0.doStartTag();
      if (_jspx_eval_aui_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("							");
        //  aui:input
        com.liferay.taglib.aui.InputTag _jspx_th_aui_005finput_005f0 = new com.liferay.taglib.aui.InputTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_aui_005finput_005f0);
        _jspx_th_aui_005finput_005f0.setPageContext(_jspx_page_context);
        _jspx_th_aui_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fform_005f0);
        // /view.jsp(152,7) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setName("filter");
        // /view.jsp(152,7) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setType("hidden");
        // /view.jsp(152,7) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setValue( currentFilter );
        // /view.jsp(152,7) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setCssClass("task-filter-input");
        int _jspx_eval_aui_005finput_005f0 = _jspx_th_aui_005finput_005f0.doStartTag();
        if (_jspx_th_aui_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005finput_005f0, _jsp_getInstanceManager());
        out.write("\n");
        out.write("							");
        //  aui:button
        com.liferay.taglib.aui.ButtonTag _jspx_th_aui_005fbutton_005f0 = new com.liferay.taglib.aui.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fbutton_005f0);
        _jspx_th_aui_005fbutton_005f0.setPageContext(_jspx_page_context);
        _jspx_th_aui_005fbutton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fform_005f0);
        // /view.jsp(153,7) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005fbutton_005f0.setType("submit");
        // /view.jsp(153,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005fbutton_005f0.setValue( task.isDone() ? "Reabrir" : "Concluir" );
        int _jspx_eval_aui_005fbutton_005f0 = _jspx_th_aui_005fbutton_005f0.doStartTag();
        if (_jspx_th_aui_005fbutton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fbutton_005f0, _jsp_getInstanceManager());
        out.write("\n");
        out.write("						");
      }
      if (_jspx_th_aui_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fform_005f0, _jsp_getInstanceManager());
      out.write("\n");
      out.write("\n");
      out.write("						");
      //  aui:form
      com.liferay.taglib.aui.FormTag _jspx_th_aui_005fform_005f1 = new com.liferay.taglib.aui.FormTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fform_005f1);
      _jspx_th_aui_005fform_005f1.setPageContext(_jspx_page_context);
      _jspx_th_aui_005fform_005f1.setParent(null);
      // /view.jsp(159,6) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f1.setAction( deleteTaskURL );
      // /view.jsp(159,6) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f1.setMethod("post");
      // /view.jsp(159,6) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f1.setCssClass("d-inline task-filter-form");
      int _jspx_eval_aui_005fform_005f1 = _jspx_th_aui_005fform_005f1.doStartTag();
      if (_jspx_eval_aui_005fform_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("							");
        //  aui:input
        com.liferay.taglib.aui.InputTag _jspx_th_aui_005finput_005f1 = new com.liferay.taglib.aui.InputTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_aui_005finput_005f1);
        _jspx_th_aui_005finput_005f1.setPageContext(_jspx_page_context);
        _jspx_th_aui_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fform_005f1);
        // /view.jsp(160,7) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setName("filter");
        // /view.jsp(160,7) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setType("hidden");
        // /view.jsp(160,7) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setValue( currentFilter );
        // /view.jsp(160,7) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setCssClass("task-filter-input");
        int _jspx_eval_aui_005finput_005f1 = _jspx_th_aui_005finput_005f1.doStartTag();
        if (_jspx_th_aui_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005finput_005f1, _jsp_getInstanceManager());
        out.write("\n");
        out.write("							");
        if (_jspx_meth_aui_005fbutton_005f1(_jspx_th_aui_005fform_005f1, _jspx_page_context))
          return;
        out.write("\n");
        out.write("						");
      }
      if (_jspx_th_aui_005fform_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fform_005f1, _jsp_getInstanceManager());
      out.write("\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					");
 if (subtasks != null && !subtasks.isEmpty()) { 
      out.write("\n");
      out.write("						<div class=\"subtask-section-title\">Subtarefas</div>\n");
      out.write("\n");
      out.write("						<ul class=\"subtask-list\">\n");
      out.write("							");
 for (Task subtask : subtasks) { 
      out.write("\n");
      out.write("								");

								String subtaskImageURL = null;

								if (taskImageUrls != null) {
									subtaskImageURL = taskImageUrls.get(subtask.getTaskId());
								}
								
      out.write("\n");
      out.write("\n");
      out.write("								<li class=\"subtask-item\" data-status=\"");
      out.print( subtask.isDone() ? "done" : "pending" );
      out.write("\">\n");
      out.write("									<div class=\"task-item-header\">\n");
      out.write("										<div class=\"task-item-main\">\n");
      out.write("											<h4 class=\"subtask-title\">");
      out.print( subtask.getTitle() );
      out.write("</h4>\n");
      out.write("\n");
      out.write("											");
 if (subtask.getDescription() != null && !subtask.getDescription().trim().isEmpty()) { 
      out.write("\n");
      out.write("												<p class=\"task-description\">");
      out.print( subtask.getDescription() );
      out.write("</p>\n");
      out.write("											");
 } 
      out.write("\n");
      out.write("										</div>\n");
      out.write("\n");
      out.write("										<span class=\"task-status-badge ");
      out.print( subtask.isDone() ? "task-status-done" : "task-status-pending" );
      out.write("\">\n");
      out.write("											");
      out.print( subtask.isDone() ? "Concluída" : "Pendente" );
      out.write("\n");
      out.write("										</span>\n");
      out.write("									</div>\n");
      out.write("\n");
      out.write("									");
 if (subtaskImageURL != null && !subtaskImageURL.isEmpty()) { 
      out.write("\n");
      out.write("										<div class=\"task-image-wrapper\">\n");
      out.write("											<img\n");
      out.write("												src=\"");
      out.print( subtaskImageURL );
      out.write("\"\n");
      out.write("												alt=\"Imagem da subtarefa\"\n");
      out.write("												class=\"task-image\"\n");
      out.write("											/>\n");
      out.write("										</div>\n");
      out.write("									");
 } 
      out.write("\n");
      out.write("\n");
      out.write("									");
      //  portlet:renderURL
      com.liferay.taglib.portlet.RenderURLTag _jspx_th_portlet_005frenderURL_005f3 = new com.liferay.taglib.portlet.RenderURLTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005frenderURL_005f3);
      _jspx_th_portlet_005frenderURL_005f3.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005frenderURL_005f3.setParent(null);
      // /view.jsp(206,9) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005frenderURL_005f3.setVar("editSubtaskURL");
      int _jspx_eval_portlet_005frenderURL_005f3 = _jspx_th_portlet_005frenderURL_005f3.doStartTag();
      if (_jspx_eval_portlet_005frenderURL_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("										");
        if (_jspx_meth_portlet_005fparam_005f8(_jspx_th_portlet_005frenderURL_005f3, _jspx_page_context))
          return;
        out.write("\n");
        out.write("										");
        //  portlet:param
        com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f9 = new com.liferay.taglib.util.ParamTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f9);
        _jspx_th_portlet_005fparam_005f9.setPageContext(_jspx_page_context);
        _jspx_th_portlet_005fparam_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005frenderURL_005f3);
        // /view.jsp(208,10) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f9.setName("taskId");
        // /view.jsp(208,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f9.setValue( String.valueOf(subtask.getTaskId()) );
        int _jspx_eval_portlet_005fparam_005f9 = _jspx_th_portlet_005fparam_005f9.doStartTag();
        if (_jspx_th_portlet_005fparam_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f9, _jsp_getInstanceManager());
        out.write("\n");
        out.write("									");
      }
      if (_jspx_th_portlet_005frenderURL_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005frenderURL_005f3, _jsp_getInstanceManager());
      java.lang.String editSubtaskURL = null;
      editSubtaskURL = (java.lang.String) _jspx_page_context.findAttribute("editSubtaskURL");
      out.write("\n");
      out.write("\n");
      out.write("									");
      //  portlet:actionURL
      com.liferay.taglib.portlet.ActionURLTag _jspx_th_portlet_005factionURL_005f2 = new com.liferay.taglib.portlet.ActionURLTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005factionURL_005f2);
      _jspx_th_portlet_005factionURL_005f2.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005factionURL_005f2.setParent(null);
      // /view.jsp(211,9) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005factionURL_005f2.setName("/task/toggle-status");
      // /view.jsp(211,9) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005factionURL_005f2.setVar("toggleSubtaskStatusURL");
      int _jspx_eval_portlet_005factionURL_005f2 = _jspx_th_portlet_005factionURL_005f2.doStartTag();
      if (_jspx_eval_portlet_005factionURL_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("										");
        //  portlet:param
        com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f10 = new com.liferay.taglib.util.ParamTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f10);
        _jspx_th_portlet_005fparam_005f10.setPageContext(_jspx_page_context);
        _jspx_th_portlet_005fparam_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005factionURL_005f2);
        // /view.jsp(212,10) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f10.setName("taskId");
        // /view.jsp(212,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f10.setValue( String.valueOf(subtask.getTaskId()) );
        int _jspx_eval_portlet_005fparam_005f10 = _jspx_th_portlet_005fparam_005f10.doStartTag();
        if (_jspx_th_portlet_005fparam_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f10, _jsp_getInstanceManager());
        out.write("\n");
        out.write("									");
      }
      if (_jspx_th_portlet_005factionURL_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005factionURL_005f2, _jsp_getInstanceManager());
      java.lang.String toggleSubtaskStatusURL = null;
      toggleSubtaskStatusURL = (java.lang.String) _jspx_page_context.findAttribute("toggleSubtaskStatusURL");
      out.write("\n");
      out.write("\n");
      out.write("									");
      //  portlet:actionURL
      com.liferay.taglib.portlet.ActionURLTag _jspx_th_portlet_005factionURL_005f3 = new com.liferay.taglib.portlet.ActionURLTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005factionURL_005f3);
      _jspx_th_portlet_005factionURL_005f3.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005factionURL_005f3.setParent(null);
      // /view.jsp(215,9) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005factionURL_005f3.setName("/task/delete");
      // /view.jsp(215,9) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_portlet_005factionURL_005f3.setVar("deleteSubtaskURL");
      int _jspx_eval_portlet_005factionURL_005f3 = _jspx_th_portlet_005factionURL_005f3.doStartTag();
      if (_jspx_eval_portlet_005factionURL_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("										");
        //  portlet:param
        com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f11 = new com.liferay.taglib.util.ParamTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f11);
        _jspx_th_portlet_005fparam_005f11.setPageContext(_jspx_page_context);
        _jspx_th_portlet_005fparam_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005factionURL_005f3);
        // /view.jsp(216,10) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f11.setName("taskId");
        // /view.jsp(216,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_portlet_005fparam_005f11.setValue( String.valueOf(subtask.getTaskId()) );
        int _jspx_eval_portlet_005fparam_005f11 = _jspx_th_portlet_005fparam_005f11.doStartTag();
        if (_jspx_th_portlet_005fparam_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f11, _jsp_getInstanceManager());
        out.write("\n");
        out.write("									");
      }
      if (_jspx_th_portlet_005factionURL_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005factionURL_005f3, _jsp_getInstanceManager());
      java.lang.String deleteSubtaskURL = null;
      deleteSubtaskURL = (java.lang.String) _jspx_page_context.findAttribute("deleteSubtaskURL");
      out.write("\n");
      out.write("\n");
      out.write("									<div class=\"task-actions\">\n");
      out.write("										<a\n");
      out.write("											class=\"btn btn-secondary task-edit-link\"\n");
      out.write("											href=\"");
      out.print( editSubtaskURL.toString() );
      out.write('&');
      out.print( namespace );
      out.write("filter=");
      out.print( currentFilter );
      out.write("\"\n");
      out.write("										>\n");
      out.write("											Editar\n");
      out.write("										</a>\n");
      out.write("\n");
      out.write("										");
      //  aui:form
      com.liferay.taglib.aui.FormTag _jspx_th_aui_005fform_005f2 = new com.liferay.taglib.aui.FormTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fform_005f2);
      _jspx_th_aui_005fform_005f2.setPageContext(_jspx_page_context);
      _jspx_th_aui_005fform_005f2.setParent(null);
      // /view.jsp(227,10) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f2.setAction( toggleSubtaskStatusURL );
      // /view.jsp(227,10) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f2.setMethod("post");
      // /view.jsp(227,10) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f2.setCssClass("d-inline task-filter-form");
      int _jspx_eval_aui_005fform_005f2 = _jspx_th_aui_005fform_005f2.doStartTag();
      if (_jspx_eval_aui_005fform_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("											");
        //  aui:input
        com.liferay.taglib.aui.InputTag _jspx_th_aui_005finput_005f2 = new com.liferay.taglib.aui.InputTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_aui_005finput_005f2);
        _jspx_th_aui_005finput_005f2.setPageContext(_jspx_page_context);
        _jspx_th_aui_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fform_005f2);
        // /view.jsp(228,11) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f2.setName("filter");
        // /view.jsp(228,11) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f2.setType("hidden");
        // /view.jsp(228,11) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f2.setValue( currentFilter );
        // /view.jsp(228,11) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f2.setCssClass("task-filter-input");
        int _jspx_eval_aui_005finput_005f2 = _jspx_th_aui_005finput_005f2.doStartTag();
        if (_jspx_th_aui_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005finput_005f2, _jsp_getInstanceManager());
        out.write("\n");
        out.write("											");
        //  aui:button
        com.liferay.taglib.aui.ButtonTag _jspx_th_aui_005fbutton_005f2 = new com.liferay.taglib.aui.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fbutton_005f2);
        _jspx_th_aui_005fbutton_005f2.setPageContext(_jspx_page_context);
        _jspx_th_aui_005fbutton_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fform_005f2);
        // /view.jsp(229,11) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005fbutton_005f2.setType("submit");
        // /view.jsp(229,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005fbutton_005f2.setValue( subtask.isDone() ? "Reabrir" : "Concluir" );
        int _jspx_eval_aui_005fbutton_005f2 = _jspx_th_aui_005fbutton_005f2.doStartTag();
        if (_jspx_th_aui_005fbutton_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fbutton_005f2, _jsp_getInstanceManager());
        out.write("\n");
        out.write("										");
      }
      if (_jspx_th_aui_005fform_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fform_005f2, _jsp_getInstanceManager());
      out.write("\n");
      out.write("\n");
      out.write("										");
      //  aui:form
      com.liferay.taglib.aui.FormTag _jspx_th_aui_005fform_005f3 = new com.liferay.taglib.aui.FormTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fform_005f3);
      _jspx_th_aui_005fform_005f3.setPageContext(_jspx_page_context);
      _jspx_th_aui_005fform_005f3.setParent(null);
      // /view.jsp(235,10) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f3.setAction( deleteSubtaskURL );
      // /view.jsp(235,10) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f3.setMethod("post");
      // /view.jsp(235,10) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fform_005f3.setCssClass("d-inline task-filter-form");
      int _jspx_eval_aui_005fform_005f3 = _jspx_th_aui_005fform_005f3.doStartTag();
      if (_jspx_eval_aui_005fform_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("											");
        //  aui:input
        com.liferay.taglib.aui.InputTag _jspx_th_aui_005finput_005f3 = new com.liferay.taglib.aui.InputTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_aui_005finput_005f3);
        _jspx_th_aui_005finput_005f3.setPageContext(_jspx_page_context);
        _jspx_th_aui_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fform_005f3);
        // /view.jsp(236,11) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f3.setName("filter");
        // /view.jsp(236,11) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f3.setType("hidden");
        // /view.jsp(236,11) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f3.setValue( currentFilter );
        // /view.jsp(236,11) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f3.setCssClass("task-filter-input");
        int _jspx_eval_aui_005finput_005f3 = _jspx_th_aui_005finput_005f3.doStartTag();
        if (_jspx_th_aui_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005finput_005f3, _jsp_getInstanceManager());
        out.write("\n");
        out.write("											");
        if (_jspx_meth_aui_005fbutton_005f3(_jspx_th_aui_005fform_005f3, _jspx_page_context))
          return;
        out.write("\n");
        out.write("										");
      }
      if (_jspx_th_aui_005fform_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fform_005f3, _jsp_getInstanceManager());
      out.write("\n");
      out.write("									</div>\n");
      out.write("								</li>\n");
      out.write("							");
 } 
      out.write("\n");
      out.write("						</ul>\n");
      out.write("					");
 } 
      out.write("\n");
      out.write("				</li>\n");
      out.write("			");
 } 
      out.write("\n");
      out.write("		</ul>\n");
      out.write("	");
 } 
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("(function() {\n");
      out.write("	const namespace = '");
      out.print( namespace );
      out.write("';\n");
      out.write("	const tabsContainer = document.getElementById(namespace + 'taskTabs');\n");
      out.write("	const currentFilterInput = document.getElementById(namespace + 'currentFilter');\n");
      out.write("	const newTaskLink = document.getElementById(namespace + 'newTaskLink');\n");
      out.write("\n");
      out.write("	if (!tabsContainer) {\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	const tabs = tabsContainer.querySelectorAll('.task-tab');\n");
      out.write("	const items = document.querySelectorAll('.task-item, .subtask-item');\n");
      out.write("	const editLinks = document.querySelectorAll('.task-edit-link');\n");
      out.write("	const filterInputs = document.querySelectorAll('.task-filter-input');\n");
      out.write("\n");
      out.write("	function updateLinksAndForms(filter) {\n");
      out.write("		currentFilterInput.value = filter;\n");
      out.write("\n");
      out.write("		if (newTaskLink) {\n");
      out.write("			const url = new URL(newTaskLink.href, window.location.origin);\n");
      out.write("			url.searchParams.set(namespace + 'filter', filter);\n");
      out.write("			newTaskLink.href = url.pathname + url.search;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		editLinks.forEach(function(link) {\n");
      out.write("			const url = new URL(link.href, window.location.origin);\n");
      out.write("			url.searchParams.set(namespace + 'filter', filter);\n");
      out.write("			link.href = url.pathname + url.search;\n");
      out.write("		});\n");
      out.write("\n");
      out.write("		filterInputs.forEach(function(input) {\n");
      out.write("			input.value = filter;\n");
      out.write("		});\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	function applyFilter(filter) {\n");
      out.write("		items.forEach(function(item) {\n");
      out.write("			const status = item.getAttribute('data-status');\n");
      out.write("\n");
      out.write("			if (filter === 'all' || status === filter) {\n");
      out.write("				item.style.display = '';\n");
      out.write("			}\n");
      out.write("			else {\n");
      out.write("				item.style.display = 'none';\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("\n");
      out.write("		tabs.forEach(function(tab) {\n");
      out.write("			tab.classList.remove('task-tab-active');\n");
      out.write("\n");
      out.write("			if (tab.getAttribute('data-filter') === filter) {\n");
      out.write("				tab.classList.add('task-tab-active');\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("\n");
      out.write("		updateLinksAndForms(filter);\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	tabs.forEach(function(tab) {\n");
      out.write("		tab.addEventListener('click', function() {\n");
      out.write("			applyFilter(tab.getAttribute('data-filter'));\n");
      out.write("		});\n");
      out.write("	});\n");
      out.write("\n");
      out.write("	applyFilter(currentFilterInput.value || 'all');\n");
      out.write("})();\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_portlet_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_portlet_005frenderURL_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:param
    com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f0 = new com.liferay.taglib.util.ParamTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f0);
    _jspx_th_portlet_005fparam_005f0.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005frenderURL_005f0);
    // /view.jsp(33,1) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_portlet_005fparam_005f0.setName("mvcRenderCommandName");
    // /view.jsp(33,1) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_portlet_005fparam_005f0.setValue("/task/form");
    int _jspx_eval_portlet_005fparam_005f0 = _jspx_th_portlet_005fparam_005f0.doStartTag();
    if (_jspx_th_portlet_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_portlet_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_portlet_005frenderURL_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:param
    com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f1 = new com.liferay.taglib.util.ParamTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f1);
    _jspx_th_portlet_005fparam_005f1.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005frenderURL_005f1);
    // /view.jsp(118,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_portlet_005fparam_005f1.setName("mvcRenderCommandName");
    // /view.jsp(118,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_portlet_005fparam_005f1.setValue("/task/edit-form");
    int _jspx_eval_portlet_005fparam_005f1 = _jspx_th_portlet_005fparam_005f1.doStartTag();
    if (_jspx_th_portlet_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f1, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_portlet_005fparam_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_portlet_005frenderURL_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:param
    com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f3 = new com.liferay.taglib.util.ParamTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f3);
    _jspx_th_portlet_005fparam_005f3.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fparam_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005frenderURL_005f2);
    // /view.jsp(123,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_portlet_005fparam_005f3.setName("mvcRenderCommandName");
    // /view.jsp(123,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_portlet_005fparam_005f3.setValue("/task/form");
    int _jspx_eval_portlet_005fparam_005f3 = _jspx_th_portlet_005fparam_005f3.doStartTag();
    if (_jspx_th_portlet_005fparam_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f3, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_aui_005fbutton_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  aui:button
    com.liferay.taglib.aui.ButtonTag _jspx_th_aui_005fbutton_005f1 = new com.liferay.taglib.aui.ButtonTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fbutton_005f1);
    _jspx_th_aui_005fbutton_005f1.setPageContext(_jspx_page_context);
    _jspx_th_aui_005fbutton_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fform_005f1);
    // /view.jsp(161,7) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_aui_005fbutton_005f1.setType("submit");
    // /view.jsp(161,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_aui_005fbutton_005f1.setValue("Excluir");
    int _jspx_eval_aui_005fbutton_005f1 = _jspx_th_aui_005fbutton_005f1.doStartTag();
    if (_jspx_th_aui_005fbutton_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fbutton_005f1, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_portlet_005fparam_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_portlet_005frenderURL_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:param
    com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f8 = new com.liferay.taglib.util.ParamTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fparam_005f8);
    _jspx_th_portlet_005fparam_005f8.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fparam_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005frenderURL_005f3);
    // /view.jsp(207,10) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_portlet_005fparam_005f8.setName("mvcRenderCommandName");
    // /view.jsp(207,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_portlet_005fparam_005f8.setValue("/task/edit-form");
    int _jspx_eval_portlet_005fparam_005f8 = _jspx_th_portlet_005fparam_005f8.doStartTag();
    if (_jspx_th_portlet_005fparam_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fparam_005f8, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_aui_005fbutton_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fform_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  aui:button
    com.liferay.taglib.aui.ButtonTag _jspx_th_aui_005fbutton_005f3 = new com.liferay.taglib.aui.ButtonTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fbutton_005f3);
    _jspx_th_aui_005fbutton_005f3.setPageContext(_jspx_page_context);
    _jspx_th_aui_005fbutton_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fform_005f3);
    // /view.jsp(237,11) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_aui_005fbutton_005f3.setType("submit");
    // /view.jsp(237,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_aui_005fbutton_005f3.setValue("Excluir");
    int _jspx_eval_aui_005fbutton_005f3 = _jspx_th_aui_005fbutton_005f3.doStartTag();
    if (_jspx_th_aui_005fbutton_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fbutton_005f3, _jsp_getInstanceManager());
    return false;
  }
}
